In [5]:
import json
import pandas as pd
import sys
from PyQt5 import QtCore as qtc
from PyQt5.QtCore import QAbstractTableModel, Qt
from PyQt5 import QtWidgets as qtw
from PyQt5.QtWidgets import QApplication, QTableView

In [6]:
df = pd.read_json('/home/max/Projects/BiblionOCR/Model/Project/Data/json/PageVerseCrossReference.json')
#df

In [9]:
#row_filter = (df["Page"] == 1)
page = 32
line = 10
book = "Mat"
chapter = "1"
verse = "1"

#page_filter = (df["Page"] == page)
##line_filter = (df["PageLine"] == line)
page_line_filter = (df["Page"] == page) & (df["PageLine"] == line)

#book_filter = (df["StartBook"] == book)
#chapter_filter = (df["StartChapter"] == chapter)
#verse_filter = (df["StartVerse"] == verse)
#book_chapter_filter = (df["StartBook"] == book) & (df["StartChapter"] == chapter)
#book_chapter_verse_filter = (df["StartBook"] == book) & (df["StartChapter"] == chapter) & (df["StartVerse"] == verse)

In [10]:
#row_df = df[page_filter]
##row_df = df[line_filter]
row_df = df[page_line_filter]

table_df = row_df[["Page","PageLine","StartBook","StartChapter","StartVerse"]]
table_df

      Page  PageLine StartBook StartChapter StartVerse
1222    32        10       Mat           13         49

In [38]:
df.loc[book_chapter_verse_filter,["Page","PageLine","StartBook","StartChapter","StartVerse"]]

      Page  PageLine StartBook StartChapter StartVerse
0        1         1       Mat            1          1
1        1         2       Mat            1          1
2        1         3       Mat            1          1
3        1         4       Mat            1          1
4        1         5       Mat            1          1
24       2         1       Mat            1          1
225      6        41       Mat            1          1
1135    29        39       Mat            1          1
1720    44        39       Mat            1          1
2040    52        41       Mat            1          1
2082    53        41       Mat            1          1
2083    54         1       Mat            1          1
2172    56        10       Mat            1          1
2174    56        12       Mat            1          1
2175    56        13       Mat            1          1
2180    56        18       Mat            1          1
2181    56        19       Mat            1          1
2183    56        21       Mat            1          1
5401   138         1       Mat            1          1

In [4]:
class pandasModel(QAbstractTableModel):

    def __init__(self, data):
        QAbstractTableModel.__init__(self)
        self._data = data

    def rowCount(self, parent=None):
        return self._data.shape[0]

    def columnCount(self, parnet=None):
        return self._data.shape[1]

    def data(self, index, role=Qt.DisplayRole):
        if index.isValid():
            if role == Qt.DisplayRole:
                return str(self._data.iloc[index.row(), index.column()])
        return None

    def headerData(self, col, orientation, role):
        if orientation == Qt.Horizontal and role == Qt.DisplayRole:
            return self._data.columns[col]
        return None

In [5]:
app = QApplication(sys.argv)
model = pandasModel(table_df)
view = QTableView()
view.setModel(model)
view.resize(800, 600)
view.show()
sys.exit(app.exec_())

SystemExit: 0

/home/max/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3351: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)